FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/shared/package.json packages/shared/package.json

RUN npm install

COPY . .

RUN npm run --workspace @wiki/shared build
RUN npm run --workspace @wiki/api build

EXPOSE 4000

CMD ["npm", "run", "--workspace", "@wiki/api", "start"]
